language: bash

sudo: required
dist: trusty

os:
  - linux
  - osx

# Install dependencies
addons:
  apt:
    packages:
    - squashfs-tools

env:
  global:
    - ELIXIR_VERSION=1.4.5 ERLANG_VERSION=19.3
  matrix:
    - MIX_TARGET=rpi
    - MIX_TARGET=rpi2
    - MIX_TARGET=rpi3
    - MIX_TARGET=bbb

before_install:
  - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.3.0
  - source ~/.asdf/asdf.sh
  - asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
  - asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
  - asdf install erlang $ERLANG_VERSION
  - asdf install elixir $ELIXIR_VERSION
  - asdf global erlang $ERLANG_VERSION
  - asdf global elixir $ELIXIR_VERSION
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      wget https://github.com/fhunleth/fwup/releases/download/v0.15.3/fwup_0.15.3_amd64.deb;
      sudo dpkg -i fwup_0.15.3_amd64.deb;
    else
      brew update;
      brew install fwup;
      brew install squashfs;
      brew unlink coreutils;
      brew install coreutils;
    fi

script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez --force
  - pushd blinky
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd hello_gpio
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd hello_gpio_input
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd hello_leds
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd hello_network
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd hello_phoenix/apps/fw
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - pushd hello_wifi
  - mix do deps.get, firmware --verbosity=verbose
  - popd
  - if [[ "$MIX_TARGET" == rpi* ]]; then
      pushd neopixel;
      mix do deps.get, firmware --verbosity=verbose;
      popd;
    fi
